version: "3.8"
networks:
  backend:
  frontend:
  selenium:
services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
  chrome_server:
    image: seleniarm/standalone-chromium
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium
  app:
    build: .
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    env_file: 
      - .env
    command: script/docker-dev-start-web.sh
    networks:
      - backend
      - frontend
      - selenium
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes: 
  redis:
  db:
